source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

platform :ios, '8.0'
# ignore all warnings from all pods(注解)
inhibit_all_warnings!
platform:ios

target 'PicSh' do
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'FMDB'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts target.name
  end
end
