(function($){var body=$('body'),_window=$(window),nav,button,menu;nav=$('#primary-navigation');button=nav.find('.menu-toggle');menu=nav.find('.nav-menu');(function(){if(!nav||!button){return;}
if(!menu||!menu.children().length){button.hide();return;}
button.on('click.twentyfourteen',function(){nav.toggleClass('toggled-on');if(nav.hasClass('toggled-on')){$(this).attr('aria-expanded','true');menu.attr('aria-expanded','true');}else{$(this).attr('aria-expanded','false');menu.attr('aria-expanded','false');}});})();_window.on('hashchange.twentyfourteen',function(){var hash=location.hash.substring(1),element;if(!hash){return;}
element=document.getElementById(hash);if(element){if(!/^(?:a|select|input|button|textarea)$/i.test(element.tagName)){element.tabIndex=-1;}
element.focus();window.scrollBy(0,-80);}});$(function(){$('.search-toggle').on('click.twentyfourteen',function(event){var that=$(this),wrapper=$('#search-container'),container=that.find('a');that.toggleClass('active');wrapper.toggleClass('hide');if(that.hasClass('active')){container.attr('aria-expanded','true');}else{container.attr('aria-expanded','false');}
if(that.is('.active')||$('.search-toggle .screen-reader-text')[0]===event.target){wrapper.find('.search-field').focus();}});if(_window.width()>781){var mastheadHeight=$('#masthead').height(),toolbarOffset,mastheadOffset;if(mastheadHeight>48){body.removeClass('masthead-fixed');}
if(body.is('.header-image')){toolbarOffset=body.is('.admin-bar')?$('#wpadminbar').height():0;mastheadOffset=$('#masthead').offset().top- toolbarOffset;_window.on('scroll.twentyfourteen',function(){if(_window.scrollTop()>mastheadOffset&&mastheadHeight<49){body.addClass('masthead-fixed');}else{body.removeClass('masthead-fixed');}});}}
$('.primary-navigation, .secondary-navigation').find('a').on('focus.twentyfourteen blur.twentyfourteen',function(){$(this).parents().toggleClass('focus');});});function onResizeARIA(){if(781>_window.width()){button.attr('aria-expanded','false');menu.attr('aria-expanded','false');button.attr('aria-controls','primary-menu');}else{button.removeAttr('aria-expanded');menu.removeAttr('aria-expanded');button.removeAttr('aria-controls');}}
_window.on('load.twentyfourteen',onResizeARIA).on('resize.twentyfourteen',function(){onResizeARIA();});_window.load(function(){if($.isFunction($.fn.masonry)){$('#footer-sidebar').masonry({itemSelector:'.widget',columnWidth:function(containerWidth){return containerWidth/4;},gutterWidth:0,isResizable:true,isRTL:$('body').is('.rtl')});}
if(body.is('.slider')){$('.featured-content').featuredslider({selector:'.featured-content-inner > article',controlsContainer:'.featured-content'});}});})(jQuery);